### ISSUE TITLE
Document usage of class names

### ISSUE THREAD

**Issue by jvmartins** [davidchin/react-input-range#30]
We can check possibilities for class names in the file:
https://github.com/davidchin/react-input-range/blob/master/src/InputRange/defaultClassNames.js

But would be nice to have in the README.md a usage documentation for class names and also demo showing a setup example.

**Comment by gilles-yvetot** [comment]
Yeah I have a simple boilerplate with webpack (css-loader and style-loader) and try to use the component but it is not working.

I have the component but not the style. I tried to import/require it from the node_modules, I tried to copy-paste it in my own css file. Nothing work. I am sure it is because I am a newbie with webpack but it is very frustrating :(

**Comment by davidchin** [comment]
Thanks for raising this issue. The [README](https://github.com/davidchin/react-input-range#types) has been updated to list out all the accepted CSS class names. :)
