### ISSUE TITLE
How to use with a owner component?

### ISSUE THREAD

**Issue by amannn** [davidchin/react-input-range#4]
I want to use this component within another React component. onChange I would like to print the current value of the slider within the owner component. To do this, I call setState on every onChange to make the value available for my components render. This causes InputRange to freeze.

This shows the issue: http://codepen.io/anon/pen/zvzodN

Here I'm calling setState directly on the component itself, but it's the same if I call it on an owner.

Could you tell me what the problem is?

**Comment by davidchin** [comment]
I think the reason why you had a stack overflow is because `onChange` callback is triggered when there's a change in the component's state. Therefore, calling `setState` inside `onChange` will create a recursive loop. I added a check in a7518077ebf24cb3db6897cba8e9f8f979fd4536 so that not all state changes will trigger an update.

Anyhow, I think to achieve what you want, you have to retain the changed value of the component so that next time when `render` method of your owner component gets executed, the re-render uses the latest value instead.

For example:
```{js}
onChange(component, values) {
  this.state.values = values;
  this.setState({ hello: 'hello' });
}
render() {
  return (
    <InputRange values={this.state.values} onChange={this.onChange.bind(this)} />
  );
}
```

**Comment by amannn** [comment]
Wow, thank you for your help! That was really fast :). Maybe I can help out on something in the future :)
